#!/usr/bin/env node
// Generate NOTICE from the dependency graph that is actually distributed.
//
// # Why this is generated rather than written
//
// Anima-Engine is dual-licensed under MIT OR Apache-2.0. That first-party license does not remove
// the obligation to attribute permissive components shipped inside the binary — MIT and BSD require
// the copyright notice and licence text to travel with the distribution, and Apache-2.0 adds a
// NOTICE-propagation clause.
//
// # What this file is, and what it is not
//
// NOTICE is the **inventory**: who is in the product, under what declared licence. The licence
// **texts** those licences require live in `licensing/THIRD_PARTY_LICENSES.txt`, generated by
// `scripts/gen_third_party_licenses.mjs`. Splitting them is deliberate — the inventory is a page a
// person reads, the texts are a megabyte a person greps — but neither discharges the other's
// obligation, and for a long time this file said so about a text bundle that did not exist.
//
// # Scope
//
// Both graphs come from `scripts/lib/licensing.mjs`, which is also what the SBOM and the licence
// bundle read, so the three artifacts cannot disagree about what ships. See that file for why the
// npm side has two closures rather than one, and why the installed one is not the shipped one.
//
// Usage: node scripts/gen_notice.mjs [--check]
//   --check  exit 1 if NOTICE is out of date instead of rewriting it (for CI)

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { byteCompare, cargoInventory, npmInventory } from './lib/licensing.mjs';

const ROOT = process.cwd();
const CHECK = process.argv.includes('--check');
const NOTICE = join(ROOT, 'NOTICE');

const cargo = cargoInventory(ROOT);
const npm = npmInventory(ROOT);

const npmDistributed = npm.components.filter((c) => c.distributed);
const npmInstallOnly = npm.components.filter((c) => !c.distributed);

/** Group by declared licence, largest group first, so the long tail is at the bottom. */
function group(items) {
  const byLicense = new Map();
  for (const it of items) {
    const key = spdxOf(it) ?? 'NOT DECLARED';
    if (!byLicense.has(key)) byLicense.set(key, []);
    byLicense.get(key).push(it);
  }
  return [...byLicense.entries()].sort((a, b) => b[1].length - a[1].length || byteCompare(a[0], b[0]));
}

function section(title, items) {
  if (items.length === 0) return `### ${title}\n\n_none_\n`;
  let out = `### ${title} — ${items.length} component(s)\n`;
  for (const [license, list] of group(items)) {
    out += `\n#### ${license} (${list.length})\n\n`;
    for (const it of [...list].sort((a, b) => byteCompare(a.name, b.name) || byteCompare(a.version, b.version))) {
      out += `- ${it.name} ${it.version}${it.repository ? ` — ${it.repository}` : ''}\n`;
    }
  }
  return out;
}

// The residual gap is read from the licence bundle's own index rather than restated here, so this
// file cannot claim a smaller number than the artifact that would have to back it up.
const indexPath = join(ROOT, 'licensing', 'third-party-index.json');
if (!existsSync(indexPath)) {
  throw new Error(
    'licensing/third-party-index.json is missing. Run `node scripts/gen_third_party_licenses.mjs` ' +
      'first: NOTICE reports that artifact’s coverage and must not guess at it.',
  );
}
const index = JSON.parse(readFileSync(indexPath, 'utf8'));
const unresolved = index.unresolved;
const covered = cargo.components.length + npmDistributed.length - unresolved.length;

/**
 * The SPDX expression the licence index settled on, not a second opinion computed here.
 *
 * `@oxc-project/runtime` is why this is not just `c.declaredLicense`: rolldown compiles its helpers
 * into `dist/` and it is never installed, so there is no local manifest to read, and the expression
 * comes from the registry via `licensing/upstream/sources.json`. Reading it back from the index is
 * what keeps NOTICE and the licence bundle from disagreeing about the same component — the failure
 * this whole set of generators was consolidated to prevent.
 */
const spdxByPurl = new Map(index.components.map((c) => [c.purl, c.spdx]));
function spdxOf(component) {
  return spdxByPurl.has(component.purl) ? spdxByPurl.get(component.purl) : component.declaredLicense;
}

const undeclared = [...cargo.components, ...npmDistributed].filter((c) => !spdxOf(c));
const vendored = index.counts.fromVendoredUpstream;

const body = `# NOTICE

Anima-Engine is dual-licensed under MIT OR Apache-2.0; see [LICENSE-MIT](LICENSE-MIT) and
[LICENSE-APACHE](LICENSE-APACHE). Copyright 2026 Duong Nguyen Anh.

This file records the separate obligations for third-party components distributed with
Anima-Engine. MIT/BSD require their copyright notice and licence text to travel with the
distribution, while Apache-2.0 adds a NOTICE-propagation clause.

**This file is generated — do not edit by hand.** Regenerate with \`node scripts/gen_notice.mjs\`,
and verify in CI with \`node scripts/gen_notice.mjs --check\`.

## Where the licence texts are

This file is the **inventory**. The licence texts themselves — the thing MIT and BSD actually
require to accompany the distribution — are in
[\`licensing/THIRD_PARTY_LICENSES.txt\`](licensing/THIRD_PARTY_LICENSES.txt), taken from the exact
installed versions with a SHA-256 per source file recorded in
[\`licensing/third-party-index.json\`](licensing/third-party-index.json).

Coverage: **${covered} of ${cargo.components.length + npmDistributed.length}** distributed components
have their licence text packaged. **${vendored}** of those publish no licence file in their artifact
at all; for them the text is taken from the upstream repository at the immutable commit the release
was published from, vendored verbatim under [\`licensing/upstream/\`](licensing/upstream/) and hashed,
with the evidence tying each commit to each released version in
[\`licensing/upstream/sources.json\`](licensing/upstream/sources.json). Text read out of the installed
artifact is always preferred to a vendored copy.

The remaining **${unresolved.length}** are enumerated with the reason, and with what was searched, in
[\`licensing/UNRESOLVED.md\`](licensing/UNRESOLVED.md). No text is invented to cover for that.

## What is counted, and why

Three closures, which are genuinely different sets. Conflating them is the error this section exists
to prevent — the earlier version of this file did, in both directions at once.

- **Rust — ${cargo.components.length} crates.** Everything reachable by
  \`cargo tree --features desktop -e normal\`. \`desktop\` is the feature set \`npm run tauri:build\`
  passes, so it is what ships. \`-e normal\` excludes dev-dependencies (test-only) and
  build-dependencies (run at build time, not linked). \`cargo tree\` resolves for the **host target**,
  so this list describes a Windows build; another OS links a different set.
- **npm, distributed — ${npmDistributed.length} components.** Packages with rendered bytes in
  \`dist/\`, measured by the bundler during \`npm run build\` and recorded in
  [\`licensing/bundle-closure.json\`](licensing/bundle-closure.json). This includes
  ${npm.components.filter((c) => c.origin === 'toolchain-injected').length} components the toolchain
  compiles into the output rather than resolving from \`node_modules\` — they are **not** production
  dependencies and no reading of \`package.json\` can find them.
- **npm, installed but not distributed — ${npmInstallOnly.length} components.** In the production
  install closure, with no bytes in \`dist/\`. \`node_modules\` is not shipped, so these leave nothing
  in the product; they are listed for completeness and clearly separated, not attributed as though
  they were distributed.
- **Excluded:** workspace members (\`anima-engine\`, \`anima-domain\`) — first-party, covered by
  \`LICENSE-MIT\` and \`LICENSE-APACHE\`.

Version numbers are the resolved ones from the lockfiles at generation time. Licence strings are the
SPDX expressions each component declares in its own manifest — or, for a component the toolchain
compiles in and never installs, the expression its registry publishes for that exact version, taken
from [\`licensing/upstream/sources.json\`](licensing/upstream/sources.json) with the evidence. Where a
component declares a dual licence (commonly \`MIT OR Apache-2.0\` in the Rust ecosystem) the choice is
the distributor's, and this repository makes none on the owner's behalf: every licence file present
at the pinned release is packaged, not one option out of several.

## Rust components

${section('Crates linked into the desktop binary', cargo.components)}

## JavaScript components — distributed

${section('Packages with bytes in dist/', npmDistributed)}

## JavaScript components — installed, not distributed

These are resolved by \`npm\` for a production install but contribute no code to \`dist/\`. They are
recorded so the difference between the install closure and the ship closure is visible rather than
assumed.

${section('Present in node_modules, absent from the product', npmInstallOnly)}

## Gaps

${
  undeclared.length === 0
    ? 'Every distributed component declares a licence in its own manifest.'
    : `The following ship but declare no machine-readable licence, and need a manual determination\nbefore any distribution:\n\n${undeclared
        .map((c) => `- ${c.name} ${c.version}`)
        .join('\n')}`
}

${
  unresolved.length === 0
    ? 'Every distributed component supplies its licence text, from its own artifact or from a pinned\nupstream revision.'
    : `${unresolved.length} distributed component(s) declare a licence whose text neither their\npublished artifact nor their upstream repository contains at the released revision. They are listed\nwith the exact blocker, and with the search that failed, in\n[\`licensing/UNRESOLVED.md\`](licensing/UNRESOLVED.md) and remain open.`
}

## What this file does NOT establish

- It is an **inventory**, not a legal review. Compatibility of each third-party licence with this
  project's \`MIT OR Apache-2.0\` distribution has not been assessed, and nothing here constitutes legal sign-off.
  In particular the
  components under MPL-2.0 and the copyleft-adjacent licences are flagged for review by
  [\`docs/governance/OPEN_SOURCE_POLICY.md\`](docs/governance/OPEN_SOURCE_POLICY.md) and that review
  has not been performed.
- Copyright holders are not listed individually here. They appear in the reproduced texts in
  \`licensing/THIRD_PARTY_LICENSES.txt\`, which is where MIT's requirement actually lands.
- Coverage is asserted for the graph as generated on the host that ran the generator. A release
  built for another platform must regenerate these artifacts on that platform.
`;

if (CHECK) {
  const current = existsSync(NOTICE) ? readFileSync(NOTICE, 'utf8') : '';
  if (current !== body) {
    console.error('NOTICE is out of date with the dependency graph. Run `node scripts/gen_notice.mjs`.');
    process.exit(1);
  }
  console.log(
    `NOTICE check: up to date (${cargo.components.length} crates, ${npmDistributed.length} npm ` +
      `distributed, ${npmInstallOnly.length} npm install-only, ${unresolved.length} texts unresolved)`,
  );
} else {
  writeFileSync(NOTICE, body);
  console.log(
    `wrote NOTICE — ${cargo.components.length} Rust crates, ${npmDistributed.length} distributed npm ` +
      `components, ${npmInstallOnly.length} install-only, ${undeclared.length} without a declared licence`,
  );
}
